config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'restaurants#index'
  resources :restaurants do
    member do
      delete 'favourites', action: :destroy, controller: :favourites
      post 'favourites', action: :create, controller: :favourites
    end
  end
  resources :favourites, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user

  validates :restaurant_id, uniqueness: { scope: :user_id }
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :favourites
  has_many :favourites_by, through: :favourites, source: :user
  belongs_to :user
  belongs_to :city
  validates :name, presence: true
  validates :street, presence: true
  validates :tags, presence: true

  has_one_attached :image

  def tags=(value)
    super(sanitize_tags(value))
  end

  private

  def sanitize_tags(tags = '')
    tags.downcase.split(',').map(&:strip).uniq
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :restaurants
  has_many :favourites
  has_many :favourites_restaurants, through: :favourites, source: :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/choosing_controller.rb
class ChoosingController < ApplicationController
  def choosing_restaurant
    @restaurants = Restaurant.all.sample
    redirect_to @restaurant
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :find_restaurant, except: [:index]

  def index
    if params[:q].present?
      @restaurants = current_user.favourites_restaurants.joins(:city).where(':q = any(restaurants.tags) or restaurants.name ilike(:q) or cities.name ilike(:q)', q: params[:q])
    else
      @restaurants = current_user.favourites_restaurants
    end
  end

  def create
    unless @restaurant.favourites_by.include?(current_user)
      @restaurant.favourites_by << current_user
    end
      redirect_to @restaurant
  end

  def destroy
    favourite = Favourite.find_by!(user: current_user, restaurant: @restaurant)
    favourite.destroy
    redirect_to @restaurant
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show, :update, :edit]
  def index
    if params[:q].present?
      @restaurants = Restaurant.joins(:city).where(':q = any(restaurants.tags) or restaurants.name ilike(:q) or cities.name ilike(:q)', q: params[:q])
    else
      @restaurants = Restaurant.all
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = current_user.restaurants.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def edit
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :street, :city_id, :tags, :image)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choosing_helper.rb
module ChoosingHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/commons/_restaurants.html.erb
<div class="container">
  <div class="row" style="background-color: #f4b042;">
    <div class="col">
      Find a restaurant:
    </div>
    <div class="col">
    <%= form_tag search_path, method: :get do %>
      <div class="input-group">
        <%= text_field_tag :q, "", class: "form-control" %>
        <span class="input-group-btn">
          <%= submit_tag "Search", class: "btn btn-default" %>
        </span>
      </div>
    <% end %>
    </div>
  </div>
  <div class="row" style="background-color: #ffd99e;">
      <% restaurants.each do |restaurant| %>
        <div class="col-4" ><br>
          <div class="card text-white bg-warning mb-3">
              <% if restaurant.image.attachment.present? %>
              <%= image_tag restaurant.image, class: 'img-fluid' %>
              <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= restaurant.name %></h5>
              <p class="card-text"><%= restaurant.street %> <%= restaurant.city.name %></p>
            </div>
            <div class="card-footer">
              <p><%= link_to 'Show', restaurant_path(restaurant), class: 'badge badge-light' %></p>
            </div>
          </div>
        </div>
      <% end %>
  </div>

app/views/favourites/index.html.erb
<h2>Your favourite restaurants</h2>

<%= render 'commons/restaurants', restaurants: @restaurants, search_path: favourites_path %>
<br>
<%= link_to 'Back to the full restaurants list', restaurants_path, class: 'btn btn-warning' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Where To Eat?</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #fd7e14;">
  <a class="navbar-brand" href="#">WhereToEat</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
      <%= link_to 'Restaurants', root_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Favourites', favourites_path, class: 'nav-link' %>
        </li>
    </ul>
  </div>
    <% if user_signed_in? %>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-light' %>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-link' %>
    <% end %>
</nav>

    <div class="container">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :street %>
  <%= f.input :tags, placeholder: 'what kind of cousine is it?' %>
  <small id="emailHelp" class="form-text text-muted">Type tags separated by comma.</small>
  <p><%= f.association :city, as: :select %></p>
  <%= f.file_field :image %>
  <br><br>
<%= f.button :submit, "Save", class: "btn btn-warning" %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit restaurant</h1>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Listing restaurants</h1>

<%= render 'commons/restaurants', restaurants: @restaurants, search_path: restaurants_path %>

<br>
<%= link_to 'Add new restaurant', new_restaurant_path, class: 'btn btn-warning' %> 

app/views/restaurants/new.html.erb
<h1>Add new restaurant</h1>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %>
  <% unless @restaurant.favourites_by.include?(current_user) %>
    <%= link_to(favourites_restaurant_path(@restaurant), method: :post) do %>
      <%= icon('far', 'heart', base: "circle", class: "fa-x", style: "color:#fc8e28") %>
    <% end %>
  <% else %>
    <%= link_to(favourites_restaurant_path(@restaurant), method: :delete) do %>
      <%= icon('fas', 'heart', base: "circle", class: "fa-x", style: "color:#fc8e28") %>
    <% end %>
  <% end %>
</h2>

  <% if @restaurant.image.attachment.present? %>
    <%= image_tag @restaurant.image, class: 'img-fluid' %>
  <% end %>
<p>
  <strong>Address:</strong>
  <br>
  <%= @restaurant.street %>
  <br>
  <%= @restaurant.city.name %>
  <br>
  <strong>Tags:</strong>
  <span class="badge badge-pill badge-warning"><%= @restaurant.tags.join(', ') %></span>
</p>

<br>

<%= link_to 'Back', restaurants_path, class: 'btn btn-warning' %>
<% if @restaurant.user == current_user %>
  <%= link_to 'Edit', edit_restaurant_path(@restaurant), class: 'btn btn-warning' %>
<% end %>